### PR TITLE
Tanndlin/force single server

### LINKED ISSUE #723: Idiot proof server assertion
Since Lion is only supposed to run in **one** server, I propose that we enforce that.

We should error out instead of running if more than one guild is detected to prevent commands being run in the wrong server

@c650 whatcha think

### PR DESCRIPTION
**Pull request by tanndlin**
fixes #723

### CODE REVIEW

**Comment by tanndlin** [comment]
This would kill the client on ready if in multiple guilds

File: src/app/listener.ts [hunk 1]
```diff
@@ -29,6 +29,18 @@ export class Listener {
...
     this.container.clientService.on('ready', async () => {
+      // Enforce only one server
+      if (this.container.clientService.guilds.cache.size > 1) {
+        this.container.loggerService.error(
+          'More than one server detected. This bot is intented to run in only one server, ' +
+            'and can cause issues when in multiple.\n Please remove this bot from other ' +
+            'servers, or create a new application for Lion.'
+        );
+
+        this.container.clientService.destroy();
```
Comment (joeydotdev) [inline src/app/listener.ts:40]: why not just throw Error? the program shouldnt be running if we're in this state

Comment (tanndlin) [reply src/app/listener.ts:40]: Destroy kills the client, I cant throw an unhandled error and crash it instead if you want
